# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    api_key = app_store_connect_api_key(
			key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
			key_filepath: "./AppstoreConnectKey/AuthKey_54339S95RY.p8"
			)
    increment_build_number(xcodeproj: "AveragePriceCalculator.xcodeproj")
    build_app(scheme: "AveragePriceCalculator")
    upload_to_testflight(api_key: api_key)
    clean_up
  end

  desc "Clean up .ipa files"
  lane :clean_up do
    sh "rm -rf ../*.ipa"
    sh "rm -rf ../*.app.dSYM.zip"
    UI.message("Deleted ipa_files")
  end
end
